#!/usr/bin/env bash
# vendor-pyodide.sh — download a pinned Pyodide release, sha256-verify the
# tarball, extract only the files the latex2arxiv worker needs, and emit
# browser-extension/pyodide/integrity.json so the integrity test can re-verify
# in CI.
#
# Why: MV3 forbids remotely-hosted code at Chrome Web Store review. The
# extension ships the runtime alongside the .crx instead of fetching from
# jsDelivr at boot.
#
# Idempotency: if pyodide/integrity.json already exists and verifies, the
# script exits early without touching the network.
#
# Refresh recipe (bumping Pyodide):
#   1. Update PYODIDE_VERSION + TARBALL_SHA256 below.
#   2. Delete browser-extension/pyodide/.
#   3. Re-run this script. Commit the diff.

set -euo pipefail

PYODIDE_VERSION="0.29.4"
TARBALL_SHA256="10a44a5f851396bbd7bce73ebae7168aced12fed004dd9c3f92fa59f8887cfa6"

# Files copied from the extracted tarball into the vendored dir. Trimmed from
# the full ~408 MB distribution to ~13 MB by keeping only the runtime core
# plus the four wheels micropip + our pipeline transitively need at install
# time (Pillow for image resize, pyyaml for arxiv_config.yaml, regex for the
# portable ReDoS guard, micropip itself to install latex2arxiv).
CORE_FILES=(
  "pyodide.js"
  "pyodide.asm.js"
  "pyodide.asm.wasm"
  "pyodide-lock.json"
  "python_stdlib.zip"
)
# Pyodide's release tarball does not include LICENSE; MPL-2.0 attribution
# lives in browser-extension/README.md per upstream license terms.
PKG_WHEELS=(
  "micropip-0.11.1-py3-none-any.whl"
  "pillow-11.3.0-cp313-cp313-pyemscripten_2025_0_wasm32.whl"
  "pyyaml-6.0.2-cp313-cp313-pyemscripten_2025_0_wasm32.whl"
  "regex-2024.11.6-cp313-cp313-pyemscripten_2025_0_wasm32.whl"
)

# Resolve sha256 helper portably (macOS + Linux).
if command -v sha256sum >/dev/null 2>&1; then
  sha256() { sha256sum "$1" | awk '{print $1}'; }
else
  sha256() { shasum -a 256 "$1" | awk '{print $1}'; }
fi

# Locate browser-extension/pyodide relative to this script so the user can
# invoke it from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)/pyodide"
INTEGRITY_JSON="${DEST_DIR}/integrity.json"

# Fast-path: integrity already passes → nothing to do.
if [[ -f "${INTEGRITY_JSON}" ]]; then
  echo "vendor-pyodide.sh: pyodide/integrity.json present — verifying…"
  verify_ok=1
  # Each entry lives on one line: `{ "path": "X", "sha256": "Y" }`. Match
  # lines that carry BOTH fields so the case branch fires once per entry
  # rather than skipping the sha check (the earlier two-branch version
  # only ever extracted the path).
  while IFS= read -r line; do
    case "${line}" in
      *'"path"'*'"sha256"'*)
        path=$(printf '%s' "${line}" | sed -E 's/.*"path"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')
        expected=$(printf '%s' "${line}" | sed -E 's/.*"sha256"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')
        actual=$(sha256 "${DEST_DIR}/${path}" 2>/dev/null || echo "MISSING")
        if [[ "${actual}" != "${expected}" ]]; then
          echo "  MISMATCH ${path}: expected ${expected:0:12}…, got ${actual:0:12}…"
          verify_ok=0
        fi
        ;;
    esac
  done < "${INTEGRITY_JSON}"
  if (( verify_ok == 1 )); then
    echo "  all files verified."
    exit 0
  fi
  echo "  integrity check failed — re-vendoring."
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

TARBALL_URL="https://github.com/pyodide/pyodide/releases/download/${PYODIDE_VERSION}/pyodide-${PYODIDE_VERSION}.tar.bz2"
TARBALL_PATH="${WORK_DIR}/pyodide.tar.bz2"

echo "vendor-pyodide.sh: downloading ${TARBALL_URL}"
curl -fsSL -o "${TARBALL_PATH}" "${TARBALL_URL}"

actual_tarball_hash=$(sha256 "${TARBALL_PATH}")
if [[ "${actual_tarball_hash}" != "${TARBALL_SHA256}" ]]; then
  echo "ERROR: tarball sha256 mismatch"
  echo "  expected ${TARBALL_SHA256}"
  echo "  got      ${actual_tarball_hash}"
  exit 1
fi
echo "  tarball verified (${actual_tarball_hash:0:12}…)"

echo "vendor-pyodide.sh: extracting…"
tar -xjf "${TARBALL_PATH}" -C "${WORK_DIR}"
SRC_DIR="${WORK_DIR}/pyodide"

# Wipe destination so a removed file in a refresh does not linger.
rm -rf "${DEST_DIR}"
mkdir -p "${DEST_DIR}"

for f in "${CORE_FILES[@]}" "${PKG_WHEELS[@]}"; do
  if [[ ! -f "${SRC_DIR}/${f}" ]]; then
    echo "ERROR: ${f} missing from tarball — Pyodide release layout has changed"
    exit 1
  fi
  cp "${SRC_DIR}/${f}" "${DEST_DIR}/${f}"
done

# Emit integrity.json (manual newline-formatted so the file diffs cleanly).
{
  printf '{\n'
  printf '  "_comment": "Generated by browser-extension/scripts/vendor-pyodide.sh — do not hand-edit. tests/vendored-integrity.test.mjs re-verifies these hashes in CI.",\n'
  printf '  "pyodide_version": "%s",\n' "${PYODIDE_VERSION}"
  printf '  "files": [\n'
  first=1
  for f in "${CORE_FILES[@]}" "${PKG_WHEELS[@]}"; do
    h=$(sha256 "${DEST_DIR}/${f}")
    if (( first == 1 )); then
      first=0
    else
      printf ',\n'
    fi
    printf '    { "path": "%s", "sha256": "%s" }' "${f}" "${h}"
  done
  printf '\n  ]\n'
  printf '}\n'
} > "${INTEGRITY_JSON}"

echo "vendor-pyodide.sh: wrote $(ls "${DEST_DIR}" | wc -l | tr -d ' ') files to ${DEST_DIR}"
du -sh "${DEST_DIR}"
